Traceback (most recent call last):
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/wandb/cli/cli.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.login(relogin=relogin, key=key, anonymous=anon_mode, host=host, force=True)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 76, in login
    configured = _login(**kwargs)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 291, in _login
    wlogin.configure_api_key(key)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 175, in configure_api_key
    apikey.write_key(self._settings, key)
  File "/mnt/c/Users/diego/Desktop/machineLearnig_project1/.venv/lib/python3.10/site-packages/wandb/sdk/lib/apikey.py", line 210, in write_key
    raise ValueError("API key must be 40 characters long, yours was %s" % len(key))
